### ISSUE TITLE
Why transaction?

### ISSUE THREAD

**Issue by flier268** [mlockett42/litedb-async#34]
Application: Test.exe
CoreCLR Version: 8.0.424.16909
.NET Version: 8.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="LiteDB encounter an error. Details in the inner exception.", DebugException="LiteDB.Async.LiteAsyncException: LiteDB encounter an error. Details in the inner exception.")
 ---> LiteDB.Async.LiteAsyncException: LiteDB encounter an error. Details in the inner exception.
 ---> LiteDB.LiteException: Maximum number of transactions reached
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean& isNew)
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at LiteDB.LiteFileStream`1.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at LiteDB.LiteFileInfo`1.SaveAs(String filename, Boolean overwritten)
   at LiteDB.LiteStorage`1.Download(TFileId id, String filename, Boolean overwritten)
   at LiteDB.Async.LiteStorageAsync`1.<>c__DisplayClass16_0.<DownloadAsync>b__0()
   at LiteDB.Async.LiteDatabaseAsync.<>c__DisplayClass36_0`1.<EnqueueAsync>g__Function|0()
   --- End of inner exception stack trace ---
   
   
   ```
   builder.Services.AddSingleton<ILiteDatabaseAsync, LiteDatabaseAsync>(_ => new(builder.Configuration.GetConnectionString("Local")));

   ```

**Comment by flier268** [comment]
Downgrade LiteDB to 5.0.17 from 5.0.19 can fix that.
